Repository RIOT-OS/riotdocker, pull requests merged in 2021-02, with the labels that each got.

#129 riotbuild: include rapidjson extras for riotctrl
  riotbuild/requirements.txt
Labels: enhancement

#134 move hooks to riotbuild/
  riotbuild/hooks/build
Labels: bug

#135 riotbuild: bump version of pexpect and riotctrl
  riotbuild/requirements.txt
Labels: dependencies
